# Generated by Django 5.0.7 on 2025-04-14 17:08

import django.db.models.deletion
import isar.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AreaAtuacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('foto', models.FileField(upload_to=isar.models.uploadFotoArea)),
            ],
            options={
                'verbose_name_plural': 'Areas Atuacao',
            },
        ),
        migrations.CreateModel(
            name='Parceiro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('foto', models.FileField(upload_to=isar.models.uploadFotoArea)),
            ],
            options={
                'verbose_name_plural': 'Parceiros',
            },
        ),
        migrations.CreateModel(
            name='Tipo_Doc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Tipos docs',
            },
        ),
        migrations.CreateModel(
            name='Programa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('foto', models.FileField(upload_to=isar.models.uploadFotoPrograma)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('areasAtuacao', models.ManyToManyField(related_name='programas', to='isar.areaatuacao')),
            ],
            options={
                'verbose_name_plural': 'Programas',
            },
        ),
        migrations.CreateModel(
            name='ImagemProjeto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=isar.models.uploadFotoProjeto)),
                ('descricao', models.TextField()),
                ('programa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='isar.programa')),
            ],
            options={
                'verbose_name_plural': 'Imagens Projetos',
            },
        ),
        migrations.CreateModel(
            name='ImagemPrograma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=isar.models.uploadFotoPrograma)),
                ('descricao', models.TextField()),
                ('programa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='isar.programa')),
            ],
            options={
                'verbose_name_plural': 'Imagens Programas',
            },
        ),
        migrations.CreateModel(
            name='Projeto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('foto', models.FileField(upload_to=isar.models.uploadFotoProjeto)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('objetivos', models.TextField(blank=True, null=True)),
                ('parceiros', models.ManyToManyField(related_name='projetos', to='isar.parceiro')),
                ('programa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='isar.programa')),
            ],
            options={
                'verbose_name_plural': 'Programas',
            },
        ),
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_doc', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to='documents')),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='isar.tipo_doc')),
            ],
        ),
    ]
